# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutep', '0043_auto_20180413_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('size', models.CharField(blank=True, max_length=3, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('line', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl', models.CharField(blank=True, max_length=50, null=True)),
                ('deal', models.CharField(blank=True, max_length=50, null=True)),
                ('vessel', models.CharField(blank=True, max_length=50, null=True)),
                ('voyage', models.CharField(blank=True, max_length=50, null=True)),
                ('dateoutplan', models.DateField(blank=True, null=True)),
                ('pod', models.CharField(blank=True, max_length=50, null=True)),
                ('podcountry', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreightTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departuredate', models.DateField(blank=True, null=True)),
                ('arrivaldate', models.DateField(blank=True, null=True)),
                ('pot', models.CharField(blank=True, max_length=50, null=True)),
                ('arrivaldatepot', models.DateField(blank=True, null=True)),
                ('departuredatepot', models.DateField(blank=True, null=True)),
                ('daysinroute', models.IntegerField(blank=True, null=True)),
                ('arrivaldateactual', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('foot', models.IntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('mtu', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('departurestation', models.CharField(blank=True, max_length=50, null=True)),
                ('departuredate', models.DateField(blank=True, null=True)),
                ('destinationstation', models.CharField(blank=True, max_length=50, null=True)),
                ('totaldistance', models.IntegerField(blank=True, null=True)),
                ('estimatedtime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RailFreightTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Container')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='nutep.DateQueryEvent')),
                ('freightdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.FreightData')),
                ('freighttracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.FreightTracking')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Platform')),
                ('raildata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.RailData')),
            ],
        ),
        migrations.CreateModel(
            name='RailTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationstation', models.CharField(blank=True, max_length=50, null=True)),
                ('daysinroute', models.IntegerField(blank=True, null=True)),
                ('remainingdistance', models.IntegerField(blank=True, null=True)),
                ('arrivaldate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='railfreighttracking',
            name='railtracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.RailTracking'),
        ),
    ]
