# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=12, verbose_name='container')),
                ('guid', models.CharField(max_length=50, verbose_name='guid')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
            ],
        ),
    ]
