# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0052_auto_20200601_1148'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Company'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.DateQueryEvent'),
        ),
    ]
