# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-05 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0047_auto_20181105_2111'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Company'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
