# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0047_auto_20181105_2111'),
        ('contract', '0002_auto_20181105_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('doc_type', models.CharField(db_index=True, max_length=100)),
                ('extention', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractfiles', to='nutep.DateQueryEvent')),
            ],
        ),
    ]
