# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contractfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractFiles',
            new_name='ContractFile',
        ),
    ]
