# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20181106_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractfile',
            old_name='extention',
            new_name='extension',
        ),
    ]
