# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20181106_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractfile',
            name='guid',
            field=models.CharField(max_length=36),
        ),
    ]
