# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0048_auto_20181106_2212'),
        ('contract', '0006_auto_20181106_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractevent', to='nutep.DateQueryEvent')),
            ],
        ),
        migrations.RemoveField(
            model_name='contractfile',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractfile',
            name='event',
        ),
        migrations.DeleteModel(
            name='ContractFile',
        ),
    ]
