# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0048_auto_20181106_2212'),
        ('contract', '0007_auto_20181106_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Company')),
                ('contracts', models.ManyToManyField(blank=True, related_name='orders', to='contract.Contract')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderevent', to='nutep.DateQueryEvent')),
            ],
        ),
    ]
