# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20181205_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='guid',
            field=models.CharField(max_length=36),
        ),
    ]
