# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_auto_20181206_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderevents', to='nutep.DateQueryEvent'),
        ),
    ]
