# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-06 09:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_auto_20181206_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
