# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0050_auto_20181206_1111'),
        ('contract', '0012_clientorder_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='data_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdataevents', to='nutep.DateQueryEvent'),
        ),
    ]
