# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutep', '0043_auto_20180413_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('size', models.CharField(blank=True, max_length=3, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('line', models.CharField(blank=True, max_length=150, null=True)),
                ('emptyweight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('seal', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stuffing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffdate', models.DateField(blank=True, null=True)),
                ('vagon', models.CharField(blank=True, max_length=50, null=True)),
                ('cargomark', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('grossweight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('netweight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowindex', models.IntegerField(blank=True, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal_export.Container')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminalexports', to='nutep.DateQueryEvent')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='stuffs',
            field=models.ManyToManyField(related_name='containers', to='terminal_export.Stuffing'),
        ),
    ]
