# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='stuffs',
        ),
        migrations.AddField(
            model_name='stuffing',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal_export.Container'),
        ),
        migrations.AlterField(
            model_name='terminalexport',
            name='container',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal_export.Container'),
        ),
    ]
