# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0003_auto_20180417_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuffing',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='terminalexport',
            options={'ordering': ('rowindex',)},
        ),
    ]
