# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0004_auto_20180618_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='datein',
            field=models.DateField(blank=True, null=True),
        ),
    ]
