# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0005_container_datein'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='contract',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
