# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0006_container_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='terminal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
