# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0051_auto_20190514_1103'),
        ('terminal_export', '0007_container_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineDemurrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('stuffdate', models.DateField(blank=True, null=True)),
                ('freetime', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('overtime', models.IntegerField(blank=True, null=True)),
                ('emptytime', models.IntegerField(blank=True, null=True)),
                ('cargotime', models.IntegerField(blank=True, null=True)),
                ('totaldays', models.IntegerField(blank=True, null=True)),
                ('container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal_export.Container')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linedemurrages', to='nutep.DateQueryEvent')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Nomenclature')),
            ],
            options={
                'ordering': ('overtime',),
            },
        ),
    ]
