# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0008_linedemurrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedemurrage',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linedemurrage',
            name='stuffdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
