# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0009_auto_20190515_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedemurrage',
            name='emptydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
