# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0010_linedemurrage_emptydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedemurrage',
            name='cargomark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
