# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_export', '0011_linedemurrage_cargomark'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='dateout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
