# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 22:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0011_auto_20180105_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
