# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 10:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0013_userprofile_ukt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='crm_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ukt_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crm_guids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ukt_guids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None),
        ),
    ]
