# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0015_auto_20180108_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payers',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_payers_+', to='nutep.UserProfile'),
        ),
    ]
