# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0016_userprofile_payers'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, b'Revise')], null=True),
        ),
    ]
