# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0017_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
