# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0019_auto_20180110_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '\u0412\u0437\u0430\u0438\u043c\u043e\u0440\u0430\u0441\u0447\u0435\u0442\u044b'), (2, '\u0421\u043b\u0435\u0436\u0435\u043d\u0438\u0435')], null=True),
        ),
    ]
