# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 19:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import nutep.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutep', '0020_auto_20180122_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_guids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None)),
                ('ukt_guids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('INN', models.CharField(blank=True, max_length=14, null=True, verbose_name='INN')),
                ('KPP', models.CharField(blank=True, max_length=10, null=True, verbose_name='KPP')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=nutep.models.userprofile_path)),
                ('payers', models.ManyToManyField(blank=True, related_name='_company_payers_+', to='nutep.Company')),
                ('users', models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u0420\u0430\u0431\u043e\u0447\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430',
                'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0447\u0438\u0435 \u0433\u0440\u0443\u043f\u043f\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='INN',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='KPP',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='crm_guids',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='details',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='payers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ukt_guids',
        ),
    ]
