# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0022_auto_20180211_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='crm_guids',
            new_name='crm_guid',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='ukt_guids',
            new_name='ukt_guid',
        ),
    ]
