# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutep', '0025_auto_20180213_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='companies', through='nutep.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
