# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0026_company_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='crm_guid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ukt_guid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
