# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutep', '0027_auto_20180213_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('size', models.CharField(blank=True, max_length=3, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('line', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateQueryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, '\u0412\u0437\u0430\u0438\u043c\u043e\u0440\u0430\u0441\u0447\u0435\u0442\u044b'), (2, '\u0421\u043b\u0435\u0436\u0435\u043d\u0438\u0435')], null=True)),
                ('status', models.IntegerField(choices=[(300, '\u041d\u0435 \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d'), (100, '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), (200, '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043e'), (500, '\u041e\u0448\u0438\u0431\u043a\u0430')], default=300)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl', models.CharField(blank=True, max_length=50, null=True)),
                ('deal', models.CharField(blank=True, max_length=50, null=True)),
                ('vessel', models.CharField(blank=True, max_length=50, null=True)),
                ('voyage', models.CharField(blank=True, max_length=50, null=True)),
                ('dateoutplan', models.DateField(blank=True, null=True)),
                ('pod', models.CharField(blank=True, max_length=50, null=True)),
                ('podcountry', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreightTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departuredate', models.DateField(blank=True, null=True)),
                ('arrivaldate', models.DateField(blank=True, null=True)),
                ('pot', models.CharField(blank=True, max_length=50, null=True)),
                ('arrivaldatepot', models.DateField(blank=True, null=True)),
                ('departuredatepot', models.DateField(blank=True, null=True)),
                ('daysinroute', models.IntegerField(blank=True, null=True)),
                ('arrivaldateactual', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('foot', models.IntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('mtu', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('departurestation', models.CharField(blank=True, max_length=50, null=True)),
                ('departuredate', models.DateField(blank=True, null=True)),
                ('destinationstation', models.CharField(blank=True, max_length=50, null=True)),
                ('totaldistance', models.IntegerField(blank=True, null=True)),
                ('estimatedtime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RailFreightTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Container')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutep.DateQueryEvent')),
                ('freightdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.FreightData')),
                ('freighttracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.FreightTracking')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Platform')),
                ('raildata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.RailData')),
            ],
        ),
        migrations.CreateModel(
            name='RailTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationstation', models.CharField(blank=True, max_length=50, null=True)),
                ('daysinroute', models.IntegerField(blank=True, null=True)),
                ('remainingdistance', models.IntegerField(blank=True, null=True)),
                ('arrivaldate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='note',
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.AddField(
            model_name='railfreighttracking',
            name='railtracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.RailTracking'),
        ),
    ]
