# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0028_auto_20180219_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='datequeryevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Company'),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='railfreighttracking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='nutep.DateQueryEvent'),
        ),
    ]
