# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0030_auto_20180404_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='is_menu',
            field=models.BooleanField(default=True),
        ),
    ]
