# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0031_companyservice_is_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
