# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0033_companyservice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0412\u0437\u0430\u0438\u043c\u043e\u0440\u0430\u0441\u0447\u0435\u0442\u044b'), (2, '\u0421\u043b\u0435\u0436\u0435\u043d\u0438\u0435')], default=1),
            preserve_default=False,
        ),
    ]
