# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0035_auto_20180404_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='nav',
            field=models.CharField(default='#', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='client_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutep.ClientService'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='nutep.Company'),
        ),
    ]
