# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0036_auto_20180404_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dashboard_view',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
