# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0038_companyservice_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutep.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukt_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='companyservice',
            unique_together=set([('company', 'client_service')]),
        ),
        migrations.AddField(
            model_name='companynomenclature',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='nutep.Nomenclature'),
        ),
    ]
