# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0039_auto_20180411_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nomenclatures',
            field=models.ManyToManyField(blank=True, related_name='companies', through='nutep.CompanyNomenclature', to='nutep.Nomenclature'),
        ),
    ]
