# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0040_company_nomenclatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyservice',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='companyservice',
            name='order',
            field=models.ImageField(default=100, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='companynomenclature',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomencls', to='nutep.Company'),
        ),
        migrations.AlterField(
            model_name='companynomenclature',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutep.Nomenclature'),
        ),
    ]
