# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0041_auto_20180411_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
