# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0042_auto_20180411_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='container',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='freightdata',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='freighttracking',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='raildata',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='railtracking',
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0412\u0437\u0430\u0438\u043c\u043e\u0440\u0430\u0441\u0447\u0435\u0442\u044b'), (2, '\u0421\u043b\u0435\u0436\u0435\u043d\u0438\u0435'), (3, '\u042d\u043a\u0441\u043f\u043e\u0440\u0442 \u043d\u0430 \u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043b\u0435')], unique=True),
        ),
        migrations.AlterField(
            model_name='datequeryevent',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '\u0412\u0437\u0430\u0438\u043c\u043e\u0440\u0430\u0441\u0447\u0435\u0442\u044b'), (2, '\u0421\u043b\u0435\u0436\u0435\u043d\u0438\u0435'), (3, '\u042d\u043a\u0441\u043f\u043e\u0440\u0442 \u043d\u0430 \u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043b\u0435')], null=True),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='FreightData',
        ),
        migrations.DeleteModel(
            name='FreightTracking',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='RailData',
        ),
        migrations.DeleteModel(
            name='RailFreightTracking',
        ),
        migrations.DeleteModel(
            name='RailTracking',
        ),
    ]
